### ISSUE TITLE
add .nvmrc file

### ISSUE THREAD

**Issue by aalemayhu** [kyleparisi/Fluxion#2]
It would nice to know which node version you are using. Unfortunately I have to switch between older node versions for legacy systems so it's easy to end up using the wrong version. I tried running with `v10.15.3` which seems to work. Which node version are you using?

**Comment by kyleparisi** [comment]
The node version is built into electron. They have a table somewhere saying how the versions map to electron releases. So in essence you only need any version of node the start from source.
